[workspace]
members = [
  "programs/flexi-counter",
  "programs/schedulecommit",
  "programs/schedulecommit-security",
  "programs/sysvars",
  "schedulecommit/client",
  "schedulecommit/test-scenarios",
  "schedulecommit/test-security",
  "test-cloning",
  "test-issues",
  "test-ledger-restore",
  "test-runner",
  "test-tools",
  "test-magicblock-api",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.86"
borsh = { version = "1.2.1", features = ["derive", "unstable__schema"] }
cleanass = "0.0.1"
ephemeral-rollups-sdk = { path = "../../ephemeral-rollups-sdk/rust/sdk" }
integration-test-tools = { path = "test-tools" }
log = "0.4.20"
magicblock-api = { path = "../magicblock-api" }
magicblock-accounts-db = { path = "../magicblock-accounts-db", features = [ "dev-tools" ] }
magic-domain-program = { git = "https://github.com/magicblock-labs/magic-domain-program.git", rev = "eba7644", default-features = false}
magicblock-config = { path = "../magicblock-config" }
magicblock-core = { path = "../magicblock-core" }
program-flexi-counter = { path = "./programs/flexi-counter" }
program-schedulecommit = { path = "programs/schedulecommit" }
program-schedulecommit-security = { path = "programs/schedulecommit-security" }
rayon = "1.10.0"
schedulecommit-client = { path = "schedulecommit/client" }
serde = "1.0.217"
solana-program = "2.2"
solana-program-test = "2.2"
solana-rpc-client = "2.2"
solana-rpc-client-api = "2.2"
solana-sdk = "2.2"
solana-transaction-status = "2.2"
teepee = "0.0.1"
tempfile = "3.10.1"
test-tools-core = { path = "../test-tools-core" }
toml = "0.8.13"
lazy_static = "1.4.0"
tokio = "1.0"

[patch.crates-io]
# some solana dependencies have solana-storage-proto as dependency
# we need to patch them with our version, because they use protobuf-src v1.1.0
# and we use protobuf-src v2.1.1. Otherwise compilation fails
solana-storage-proto = { path = "../storage-proto" }
# same reason as above
solana-account = { git = "https://github.com/magicblock-labs/solana-account.git", rev = "7bdfefc" }
